2023-09-10 13:53:29,481:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 13:53:29,481:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 13:53:29,481:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 13:53:29,481:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:05:01,818:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:05:01,818:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:05:01,818:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:05:01,818:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:07:42,911:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:07:42,911:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:07:42,911:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:07:42,911:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:12:41,387:INFO:PyCaret ClassificationExperiment
2023-09-10 14:12:41,387:INFO:Logging name: clf-default-name
2023-09-10 14:12:41,387:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-09-10 14:12:41,387:INFO:version 3.0.4
2023-09-10 14:12:41,387:INFO:Initializing setup()
2023-09-10 14:12:41,387:INFO:self.USI: 5754
2023-09-10 14:12:41,387:INFO:self._variable_keys: {'USI', '_ml_usecase', '_available_plots', 'fold_groups_param', 'log_plots_param', 'X', 'target_param', 'gpu_n_jobs_param', 'y_test', 'gpu_param', 'pipeline', 'X_test', 'fold_shuffle_param', 'X_train', 'html_param', 'fix_imbalance', 'n_jobs_param', 'seed', 'exp_name_log', 'exp_id', 'logging_param', 'data', 'y', 'y_train', 'fold_generator', 'memory', 'is_multiclass', 'idx'}
2023-09-10 14:12:41,387:INFO:Checking environment
2023-09-10 14:12:41,387:INFO:python_version: 3.8.10
2023-09-10 14:12:41,387:INFO:python_build: ('default', 'May 26 2023 14:05:08')
2023-09-10 14:12:41,387:INFO:machine: x86_64
2023-09-10 14:12:41,387:INFO:platform: Linux-5.15.0-83-generic-x86_64-with-glibc2.29
2023-09-10 14:12:41,388:INFO:Memory: svmem(total=16523304960, available=10414940160, percent=37.0, used=4872429568, free=4390354944, active=2260918272, inactive=7791837184, buffers=536256512, cached=6724263936, shared=885153792, slab=1108840448)
2023-09-10 14:12:41,388:INFO:Physical Core: 4
2023-09-10 14:12:41,388:INFO:Logical Core: 8
2023-09-10 14:12:41,388:INFO:Checking libraries
2023-09-10 14:12:41,388:INFO:System:
2023-09-10 14:12:41,388:INFO:    python: 3.8.10 (default, May 26 2023, 14:05:08)  [GCC 9.4.0]
2023-09-10 14:12:41,388:INFO:executable: /home/sameep/Extra_Projects/DM/venv/bin/python3
2023-09-10 14:12:41,388:INFO:   machine: Linux-5.15.0-83-generic-x86_64-with-glibc2.29
2023-09-10 14:12:41,388:INFO:PyCaret required dependencies:
2023-09-10 14:12:41,401:INFO:                 pip: 23.2.1
2023-09-10 14:12:41,401:INFO:          setuptools: 68.0.0
2023-09-10 14:12:41,401:INFO:             pycaret: 3.0.4
2023-09-10 14:12:41,401:INFO:             IPython: 8.12.2
2023-09-10 14:12:41,401:INFO:          ipywidgets: 8.1.0
2023-09-10 14:12:41,401:INFO:                tqdm: 4.66.1
2023-09-10 14:12:41,401:INFO:               numpy: 1.23.5
2023-09-10 14:12:41,401:INFO:              pandas: 1.5.3
2023-09-10 14:12:41,401:INFO:              jinja2: 3.1.2
2023-09-10 14:12:41,401:INFO:               scipy: 1.10.1
2023-09-10 14:12:41,401:INFO:              joblib: 1.3.2
2023-09-10 14:12:41,401:INFO:             sklearn: 1.2.2
2023-09-10 14:12:41,401:INFO:                pyod: 1.1.0
2023-09-10 14:12:41,401:INFO:            imblearn: 0.11.0
2023-09-10 14:12:41,401:INFO:   category_encoders: 2.6.2
2023-09-10 14:12:41,401:INFO:            lightgbm: 4.0.0
2023-09-10 14:12:41,401:INFO:               numba: 0.57.1
2023-09-10 14:12:41,401:INFO:            requests: 2.31.0
2023-09-10 14:12:41,401:INFO:          matplotlib: 3.7.2
2023-09-10 14:12:41,401:INFO:          scikitplot: 0.3.7
2023-09-10 14:12:41,401:INFO:         yellowbrick: 1.5
2023-09-10 14:12:41,401:INFO:              plotly: 5.16.1
2023-09-10 14:12:41,401:INFO:    plotly-resampler: Not installed
2023-09-10 14:12:41,401:INFO:             kaleido: 0.2.1
2023-09-10 14:12:41,401:INFO:           schemdraw: 0.15
2023-09-10 14:12:41,401:INFO:         statsmodels: 0.14.0
2023-09-10 14:12:41,401:INFO:              sktime: 0.22.0
2023-09-10 14:12:41,401:INFO:               tbats: 1.1.3
2023-09-10 14:12:41,401:INFO:            pmdarima: 2.0.3
2023-09-10 14:12:41,401:INFO:              psutil: 5.9.5
2023-09-10 14:12:41,402:INFO:          markupsafe: 2.1.3
2023-09-10 14:12:41,402:INFO:             pickle5: Not installed
2023-09-10 14:12:41,402:INFO:         cloudpickle: 2.2.1
2023-09-10 14:12:41,402:INFO:         deprecation: 2.1.0
2023-09-10 14:12:41,402:INFO:              xxhash: 3.3.0
2023-09-10 14:12:41,402:INFO:           wurlitzer: 3.0.3
2023-09-10 14:12:41,402:INFO:PyCaret optional dependencies:
2023-09-10 14:12:41,424:INFO:                shap: Not installed
2023-09-10 14:12:41,424:INFO:           interpret: Not installed
2023-09-10 14:12:41,424:INFO:                umap: Not installed
2023-09-10 14:12:41,424:INFO:    pandas_profiling: Not installed
2023-09-10 14:12:41,424:INFO:  explainerdashboard: Not installed
2023-09-10 14:12:41,424:INFO:             autoviz: Not installed
2023-09-10 14:12:41,424:INFO:           fairlearn: Not installed
2023-09-10 14:12:41,424:INFO:          deepchecks: Not installed
2023-09-10 14:12:41,424:INFO:             xgboost: Not installed
2023-09-10 14:12:41,424:INFO:            catboost: Not installed
2023-09-10 14:12:41,424:INFO:              kmodes: Not installed
2023-09-10 14:12:41,424:INFO:             mlxtend: Not installed
2023-09-10 14:12:41,424:INFO:       statsforecast: Not installed
2023-09-10 14:12:41,424:INFO:        tune_sklearn: Not installed
2023-09-10 14:12:41,424:INFO:                 ray: Not installed
2023-09-10 14:12:41,424:INFO:            hyperopt: Not installed
2023-09-10 14:12:41,424:INFO:              optuna: Not installed
2023-09-10 14:12:41,424:INFO:               skopt: Not installed
2023-09-10 14:12:41,424:INFO:              mlflow: Not installed
2023-09-10 14:12:41,424:INFO:              gradio: Not installed
2023-09-10 14:12:41,424:INFO:             fastapi: Not installed
2023-09-10 14:12:41,424:INFO:             uvicorn: Not installed
2023-09-10 14:12:41,424:INFO:              m2cgen: Not installed
2023-09-10 14:12:41,425:INFO:           evidently: Not installed
2023-09-10 14:12:41,425:INFO:               fugue: Not installed
2023-09-10 14:12:41,425:INFO:           streamlit: Not installed
2023-09-10 14:12:41,425:INFO:             prophet: Not installed
2023-09-10 14:12:41,425:INFO:None
2023-09-10 14:12:41,425:INFO:Set up data.
2023-09-10 14:12:41,431:INFO:Set up train/test split.
2023-09-10 14:12:41,435:INFO:Set up index.
2023-09-10 14:12:41,435:INFO:Set up folding strategy.
2023-09-10 14:12:41,435:INFO:Assigning column types.
2023-09-10 14:12:41,437:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-09-10 14:12:41,497:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-09-10 14:12:41,499:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-09-10 14:12:41,527:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:12:41,528:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:12:41,561:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-09-10 14:12:41,562:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-09-10 14:12:41,583:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:12:41,583:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:12:41,584:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-09-10 14:12:41,617:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-09-10 14:12:41,638:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:12:41,638:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:12:41,671:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-09-10 14:12:41,692:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:12:41,693:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:12:41,693:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-09-10 14:12:41,749:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:12:41,749:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:12:41,802:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:12:41,804:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:12:41,805:INFO:Preparing preprocessing pipeline...
2023-09-10 14:12:41,806:INFO:Set up simple imputation.
2023-09-10 14:12:41,818:INFO:Finished creating preprocessing pipeline.
2023-09-10 14:12:41,821:INFO:Pipeline: Pipeline(memory=FastMemory(location=/tmp/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['Pclass', 'Sex', 'Age', 'Fare',
                                             'Embarked', 'Title', 'IsAlone'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose='deprecated'))),
                ('categorical_imputer',
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated')))],
         verbose=False)
2023-09-10 14:12:41,821:INFO:Creating final display dataframe.
2023-09-10 14:12:41,863:INFO:Setup _display_container:                     Description             Value
0                    Session id              6543
1                        Target          Survived
2                   Target type            Binary
3           Original data shape          (891, 8)
4        Transformed data shape          (891, 8)
5   Transformed train set shape          (623, 8)
6    Transformed test set shape          (268, 8)
7              Numeric features                 7
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                10
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              5754
2023-09-10 14:12:41,927:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:12:41,927:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:12:41,986:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:12:41,986:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:12:41,987:INFO:setup() successfully completed in 0.6s...............
2023-09-10 14:13:16,751:INFO:Initializing compare_models()
2023-09-10 14:13:16,751:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f2e40e23a60>, include=None, fold=5, round=4, cross_validation=True, sort=RMSE, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x7f2e40e23a60>, 'include': None, 'exclude': None, 'fold': 5, 'round': 4, 'cross_validation': True, 'sort': 'RMSE', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-09-10 14:13:16,751:INFO:Checking exceptions
2023-09-10 14:13:30,915:INFO:Initializing compare_models()
2023-09-10 14:13:30,915:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f2e40e23a60>, include=None, fold=5, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x7f2e40e23a60>, 'include': None, 'exclude': None, 'fold': 5, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-09-10 14:13:30,916:INFO:Checking exceptions
2023-09-10 14:13:30,918:INFO:Preparing display monitor
2023-09-10 14:13:30,946:INFO:Initializing Logistic Regression
2023-09-10 14:13:30,946:INFO:Total runtime is 5.928675333658854e-06 minutes
2023-09-10 14:13:30,951:INFO:SubProcess create_model() called ==================================
2023-09-10 14:13:30,951:INFO:Initializing create_model()
2023-09-10 14:13:30,951:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f2e40e23a60>, estimator=lr, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f2e40ed2df0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:13:30,952:INFO:Checking exceptions
2023-09-10 14:13:30,952:INFO:Importing libraries
2023-09-10 14:13:30,952:INFO:Copying training dataset
2023-09-10 14:13:30,956:INFO:Defining folds
2023-09-10 14:13:30,957:INFO:Declaring metric variables
2023-09-10 14:13:30,961:INFO:Importing untrained model
2023-09-10 14:13:30,965:INFO:Logistic Regression Imported successfully
2023-09-10 14:13:30,976:INFO:Starting cross validation
2023-09-10 14:13:30,977:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:13:32,924:INFO:Calculating mean and std
2023-09-10 14:13:32,927:INFO:Creating metrics dataframe
2023-09-10 14:13:32,933:INFO:Uploading results into container
2023-09-10 14:13:32,935:INFO:Uploading model into container now
2023-09-10 14:13:32,936:INFO:_master_model_container: 1
2023-09-10 14:13:32,936:INFO:_display_container: 2
2023-09-10 14:13:32,937:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=6543, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-09-10 14:13:32,937:INFO:create_model() successfully completed......................................
2023-09-10 14:13:33,033:INFO:SubProcess create_model() end ==================================
2023-09-10 14:13:33,033:INFO:Creating metrics dataframe
2023-09-10 14:13:33,042:INFO:Initializing K Neighbors Classifier
2023-09-10 14:13:33,043:INFO:Total runtime is 0.03494380315144857 minutes
2023-09-10 14:13:33,046:INFO:SubProcess create_model() called ==================================
2023-09-10 14:13:33,046:INFO:Initializing create_model()
2023-09-10 14:13:33,046:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f2e40e23a60>, estimator=knn, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f2e40ed2df0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:13:33,046:INFO:Checking exceptions
2023-09-10 14:13:33,046:INFO:Importing libraries
2023-09-10 14:13:33,046:INFO:Copying training dataset
2023-09-10 14:13:33,050:INFO:Defining folds
2023-09-10 14:13:33,050:INFO:Declaring metric variables
2023-09-10 14:13:33,054:INFO:Importing untrained model
2023-09-10 14:13:33,060:INFO:K Neighbors Classifier Imported successfully
2023-09-10 14:13:33,067:INFO:Starting cross validation
2023-09-10 14:13:33,068:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:13:34,198:INFO:Calculating mean and std
2023-09-10 14:13:34,199:INFO:Creating metrics dataframe
2023-09-10 14:13:34,204:INFO:Uploading results into container
2023-09-10 14:13:34,209:INFO:Uploading model into container now
2023-09-10 14:13:34,210:INFO:_master_model_container: 2
2023-09-10 14:13:34,210:INFO:_display_container: 2
2023-09-10 14:13:34,211:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-09-10 14:13:34,211:INFO:create_model() successfully completed......................................
2023-09-10 14:13:34,304:INFO:SubProcess create_model() end ==================================
2023-09-10 14:13:34,305:INFO:Creating metrics dataframe
2023-09-10 14:13:34,314:INFO:Initializing Naive Bayes
2023-09-10 14:13:34,314:INFO:Total runtime is 0.05612792968750001 minutes
2023-09-10 14:13:34,316:INFO:SubProcess create_model() called ==================================
2023-09-10 14:13:34,316:INFO:Initializing create_model()
2023-09-10 14:13:34,317:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f2e40e23a60>, estimator=nb, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f2e40ed2df0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:13:34,317:INFO:Checking exceptions
2023-09-10 14:13:34,317:INFO:Importing libraries
2023-09-10 14:13:34,317:INFO:Copying training dataset
2023-09-10 14:13:34,321:INFO:Defining folds
2023-09-10 14:13:34,321:INFO:Declaring metric variables
2023-09-10 14:13:34,325:INFO:Importing untrained model
2023-09-10 14:13:34,330:INFO:Naive Bayes Imported successfully
2023-09-10 14:13:34,338:INFO:Starting cross validation
2023-09-10 14:13:34,339:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:13:34,429:INFO:Calculating mean and std
2023-09-10 14:13:34,430:INFO:Creating metrics dataframe
2023-09-10 14:13:34,433:INFO:Uploading results into container
2023-09-10 14:13:34,434:INFO:Uploading model into container now
2023-09-10 14:13:34,434:INFO:_master_model_container: 3
2023-09-10 14:13:34,434:INFO:_display_container: 2
2023-09-10 14:13:34,434:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-09-10 14:13:34,434:INFO:create_model() successfully completed......................................
2023-09-10 14:13:34,523:INFO:SubProcess create_model() end ==================================
2023-09-10 14:13:34,523:INFO:Creating metrics dataframe
2023-09-10 14:13:34,532:INFO:Initializing Decision Tree Classifier
2023-09-10 14:13:34,532:INFO:Total runtime is 0.05976175467173259 minutes
2023-09-10 14:13:34,534:INFO:SubProcess create_model() called ==================================
2023-09-10 14:13:34,535:INFO:Initializing create_model()
2023-09-10 14:13:34,535:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f2e40e23a60>, estimator=dt, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f2e40ed2df0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:13:34,535:INFO:Checking exceptions
2023-09-10 14:13:34,535:INFO:Importing libraries
2023-09-10 14:13:34,535:INFO:Copying training dataset
2023-09-10 14:13:34,540:INFO:Defining folds
2023-09-10 14:13:34,541:INFO:Declaring metric variables
2023-09-10 14:13:34,544:INFO:Importing untrained model
2023-09-10 14:13:34,548:INFO:Decision Tree Classifier Imported successfully
2023-09-10 14:13:34,554:INFO:Starting cross validation
2023-09-10 14:13:34,555:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:13:34,681:INFO:Calculating mean and std
2023-09-10 14:13:34,682:INFO:Creating metrics dataframe
2023-09-10 14:13:34,686:INFO:Uploading results into container
2023-09-10 14:13:34,688:INFO:Uploading model into container now
2023-09-10 14:13:34,688:INFO:_master_model_container: 4
2023-09-10 14:13:34,688:INFO:_display_container: 2
2023-09-10 14:13:34,689:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=6543, splitter='best')
2023-09-10 14:13:34,689:INFO:create_model() successfully completed......................................
2023-09-10 14:13:34,777:INFO:SubProcess create_model() end ==================================
2023-09-10 14:13:34,777:INFO:Creating metrics dataframe
2023-09-10 14:13:34,784:INFO:Initializing SVM - Linear Kernel
2023-09-10 14:13:34,784:INFO:Total runtime is 0.06397215922673544 minutes
2023-09-10 14:13:34,789:INFO:SubProcess create_model() called ==================================
2023-09-10 14:13:34,789:INFO:Initializing create_model()
2023-09-10 14:13:34,789:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f2e40e23a60>, estimator=svm, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f2e40ed2df0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:13:34,789:INFO:Checking exceptions
2023-09-10 14:13:34,789:INFO:Importing libraries
2023-09-10 14:13:34,789:INFO:Copying training dataset
2023-09-10 14:13:34,794:INFO:Defining folds
2023-09-10 14:13:34,794:INFO:Declaring metric variables
2023-09-10 14:13:34,797:INFO:Importing untrained model
2023-09-10 14:13:34,802:INFO:SVM - Linear Kernel Imported successfully
2023-09-10 14:13:34,813:INFO:Starting cross validation
2023-09-10 14:13:34,814:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:13:34,866:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 14:13:34,877:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 14:13:34,883:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 14:13:34,887:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 14:13:34,887:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 14:13:34,899:INFO:Calculating mean and std
2023-09-10 14:13:34,901:INFO:Creating metrics dataframe
2023-09-10 14:13:34,906:INFO:Uploading results into container
2023-09-10 14:13:34,907:INFO:Uploading model into container now
2023-09-10 14:13:34,908:INFO:_master_model_container: 5
2023-09-10 14:13:34,908:INFO:_display_container: 2
2023-09-10 14:13:34,909:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=6543, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-09-10 14:13:34,909:INFO:create_model() successfully completed......................................
2023-09-10 14:13:34,996:INFO:SubProcess create_model() end ==================================
2023-09-10 14:13:34,996:INFO:Creating metrics dataframe
2023-09-10 14:13:35,004:INFO:Initializing Ridge Classifier
2023-09-10 14:13:35,005:INFO:Total runtime is 0.06764316161473592 minutes
2023-09-10 14:13:35,008:INFO:SubProcess create_model() called ==================================
2023-09-10 14:13:35,008:INFO:Initializing create_model()
2023-09-10 14:13:35,009:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f2e40e23a60>, estimator=ridge, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f2e40ed2df0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:13:35,009:INFO:Checking exceptions
2023-09-10 14:13:35,009:INFO:Importing libraries
2023-09-10 14:13:35,009:INFO:Copying training dataset
2023-09-10 14:13:35,013:INFO:Defining folds
2023-09-10 14:13:35,013:INFO:Declaring metric variables
2023-09-10 14:13:35,015:INFO:Importing untrained model
2023-09-10 14:13:35,019:INFO:Ridge Classifier Imported successfully
2023-09-10 14:13:35,030:INFO:Starting cross validation
2023-09-10 14:13:35,031:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:13:35,082:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 14:13:35,083:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 14:13:35,087:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 14:13:35,092:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 14:13:35,098:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 14:13:35,112:INFO:Calculating mean and std
2023-09-10 14:13:35,112:INFO:Creating metrics dataframe
2023-09-10 14:13:35,115:INFO:Uploading results into container
2023-09-10 14:13:35,115:INFO:Uploading model into container now
2023-09-10 14:13:35,116:INFO:_master_model_container: 6
2023-09-10 14:13:35,116:INFO:_display_container: 2
2023-09-10 14:13:35,116:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=6543, solver='auto',
                tol=0.0001)
2023-09-10 14:13:35,116:INFO:create_model() successfully completed......................................
2023-09-10 14:13:35,203:INFO:SubProcess create_model() end ==================================
2023-09-10 14:13:35,203:INFO:Creating metrics dataframe
2023-09-10 14:13:35,215:INFO:Initializing Random Forest Classifier
2023-09-10 14:13:35,215:INFO:Total runtime is 0.07114518880844116 minutes
2023-09-10 14:13:35,218:INFO:SubProcess create_model() called ==================================
2023-09-10 14:13:35,218:INFO:Initializing create_model()
2023-09-10 14:13:35,218:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f2e40e23a60>, estimator=rf, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f2e40ed2df0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:13:35,218:INFO:Checking exceptions
2023-09-10 14:13:35,218:INFO:Importing libraries
2023-09-10 14:13:35,218:INFO:Copying training dataset
2023-09-10 14:13:35,222:INFO:Defining folds
2023-09-10 14:13:35,222:INFO:Declaring metric variables
2023-09-10 14:13:35,225:INFO:Importing untrained model
2023-09-10 14:13:35,229:INFO:Random Forest Classifier Imported successfully
2023-09-10 14:13:35,236:INFO:Starting cross validation
2023-09-10 14:13:35,237:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:13:35,907:INFO:Calculating mean and std
2023-09-10 14:13:35,908:INFO:Creating metrics dataframe
2023-09-10 14:13:35,912:INFO:Uploading results into container
2023-09-10 14:13:35,913:INFO:Uploading model into container now
2023-09-10 14:13:35,913:INFO:_master_model_container: 7
2023-09-10 14:13:35,913:INFO:_display_container: 2
2023-09-10 14:13:35,914:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=6543, verbose=0, warm_start=False)
2023-09-10 14:13:35,914:INFO:create_model() successfully completed......................................
2023-09-10 14:13:36,000:INFO:SubProcess create_model() end ==================================
2023-09-10 14:13:36,000:INFO:Creating metrics dataframe
2023-09-10 14:13:36,010:INFO:Initializing Quadratic Discriminant Analysis
2023-09-10 14:13:36,011:INFO:Total runtime is 0.08440922498703003 minutes
2023-09-10 14:13:36,014:INFO:SubProcess create_model() called ==================================
2023-09-10 14:13:36,014:INFO:Initializing create_model()
2023-09-10 14:13:36,014:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f2e40e23a60>, estimator=qda, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f2e40ed2df0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:13:36,014:INFO:Checking exceptions
2023-09-10 14:13:36,014:INFO:Importing libraries
2023-09-10 14:13:36,014:INFO:Copying training dataset
2023-09-10 14:13:36,017:INFO:Defining folds
2023-09-10 14:13:36,017:INFO:Declaring metric variables
2023-09-10 14:13:36,023:INFO:Importing untrained model
2023-09-10 14:13:36,030:INFO:Quadratic Discriminant Analysis Imported successfully
2023-09-10 14:13:36,037:INFO:Starting cross validation
2023-09-10 14:13:36,039:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:13:36,183:INFO:Calculating mean and std
2023-09-10 14:13:36,184:INFO:Creating metrics dataframe
2023-09-10 14:13:36,191:INFO:Uploading results into container
2023-09-10 14:13:36,193:INFO:Uploading model into container now
2023-09-10 14:13:36,193:INFO:_master_model_container: 8
2023-09-10 14:13:36,193:INFO:_display_container: 2
2023-09-10 14:13:36,194:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-09-10 14:13:36,194:INFO:create_model() successfully completed......................................
2023-09-10 14:13:36,292:INFO:SubProcess create_model() end ==================================
2023-09-10 14:13:36,292:INFO:Creating metrics dataframe
2023-09-10 14:13:36,302:INFO:Initializing Ada Boost Classifier
2023-09-10 14:13:36,302:INFO:Total runtime is 0.08927364746729533 minutes
2023-09-10 14:13:36,307:INFO:SubProcess create_model() called ==================================
2023-09-10 14:13:36,307:INFO:Initializing create_model()
2023-09-10 14:13:36,307:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f2e40e23a60>, estimator=ada, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f2e40ed2df0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:13:36,307:INFO:Checking exceptions
2023-09-10 14:13:36,308:INFO:Importing libraries
2023-09-10 14:13:36,308:INFO:Copying training dataset
2023-09-10 14:13:36,312:INFO:Defining folds
2023-09-10 14:13:36,312:INFO:Declaring metric variables
2023-09-10 14:13:36,315:INFO:Importing untrained model
2023-09-10 14:13:36,319:INFO:Ada Boost Classifier Imported successfully
2023-09-10 14:13:36,330:INFO:Starting cross validation
2023-09-10 14:13:36,331:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:13:36,683:INFO:Calculating mean and std
2023-09-10 14:13:36,683:INFO:Creating metrics dataframe
2023-09-10 14:13:36,688:INFO:Uploading results into container
2023-09-10 14:13:36,690:INFO:Uploading model into container now
2023-09-10 14:13:36,690:INFO:_master_model_container: 9
2023-09-10 14:13:36,690:INFO:_display_container: 2
2023-09-10 14:13:36,691:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=6543)
2023-09-10 14:13:36,691:INFO:create_model() successfully completed......................................
2023-09-10 14:13:36,776:INFO:SubProcess create_model() end ==================================
2023-09-10 14:13:36,776:INFO:Creating metrics dataframe
2023-09-10 14:13:36,785:INFO:Initializing Gradient Boosting Classifier
2023-09-10 14:13:36,785:INFO:Total runtime is 0.09731411933898926 minutes
2023-09-10 14:13:36,789:INFO:SubProcess create_model() called ==================================
2023-09-10 14:13:36,790:INFO:Initializing create_model()
2023-09-10 14:13:36,790:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f2e40e23a60>, estimator=gbc, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f2e40ed2df0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:13:36,790:INFO:Checking exceptions
2023-09-10 14:13:36,790:INFO:Importing libraries
2023-09-10 14:13:36,790:INFO:Copying training dataset
2023-09-10 14:13:36,795:INFO:Defining folds
2023-09-10 14:13:36,795:INFO:Declaring metric variables
2023-09-10 14:13:36,798:INFO:Importing untrained model
2023-09-10 14:13:36,806:INFO:Gradient Boosting Classifier Imported successfully
2023-09-10 14:13:36,816:INFO:Starting cross validation
2023-09-10 14:13:36,817:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:13:37,164:INFO:Calculating mean and std
2023-09-10 14:13:37,165:INFO:Creating metrics dataframe
2023-09-10 14:13:37,175:INFO:Uploading results into container
2023-09-10 14:13:37,175:INFO:Uploading model into container now
2023-09-10 14:13:37,176:INFO:_master_model_container: 10
2023-09-10 14:13:37,176:INFO:_display_container: 2
2023-09-10 14:13:37,176:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=6543, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-09-10 14:13:37,177:INFO:create_model() successfully completed......................................
2023-09-10 14:13:37,284:INFO:SubProcess create_model() end ==================================
2023-09-10 14:13:37,284:INFO:Creating metrics dataframe
2023-09-10 14:13:37,297:INFO:Initializing Linear Discriminant Analysis
2023-09-10 14:13:37,297:INFO:Total runtime is 0.10585093100865682 minutes
2023-09-10 14:13:37,301:INFO:SubProcess create_model() called ==================================
2023-09-10 14:13:37,301:INFO:Initializing create_model()
2023-09-10 14:13:37,301:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f2e40e23a60>, estimator=lda, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f2e40ed2df0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:13:37,301:INFO:Checking exceptions
2023-09-10 14:13:37,301:INFO:Importing libraries
2023-09-10 14:13:37,302:INFO:Copying training dataset
2023-09-10 14:13:37,309:INFO:Defining folds
2023-09-10 14:13:37,309:INFO:Declaring metric variables
2023-09-10 14:13:37,314:INFO:Importing untrained model
2023-09-10 14:13:37,318:INFO:Linear Discriminant Analysis Imported successfully
2023-09-10 14:13:37,330:INFO:Starting cross validation
2023-09-10 14:13:37,331:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:13:37,445:INFO:Calculating mean and std
2023-09-10 14:13:37,446:INFO:Creating metrics dataframe
2023-09-10 14:13:37,451:INFO:Uploading results into container
2023-09-10 14:13:37,451:INFO:Uploading model into container now
2023-09-10 14:13:37,452:INFO:_master_model_container: 11
2023-09-10 14:13:37,452:INFO:_display_container: 2
2023-09-10 14:13:37,452:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-09-10 14:13:37,452:INFO:create_model() successfully completed......................................
2023-09-10 14:13:37,584:INFO:SubProcess create_model() end ==================================
2023-09-10 14:13:37,584:INFO:Creating metrics dataframe
2023-09-10 14:13:37,598:INFO:Initializing Extra Trees Classifier
2023-09-10 14:13:37,598:INFO:Total runtime is 0.1108721931775411 minutes
2023-09-10 14:13:37,601:INFO:SubProcess create_model() called ==================================
2023-09-10 14:13:37,602:INFO:Initializing create_model()
2023-09-10 14:13:37,602:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f2e40e23a60>, estimator=et, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f2e40ed2df0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:13:37,602:INFO:Checking exceptions
2023-09-10 14:13:37,602:INFO:Importing libraries
2023-09-10 14:13:37,602:INFO:Copying training dataset
2023-09-10 14:13:37,610:INFO:Defining folds
2023-09-10 14:13:37,610:INFO:Declaring metric variables
2023-09-10 14:13:37,614:INFO:Importing untrained model
2023-09-10 14:13:37,619:INFO:Extra Trees Classifier Imported successfully
2023-09-10 14:13:37,636:INFO:Starting cross validation
2023-09-10 14:13:37,638:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:13:38,459:INFO:Calculating mean and std
2023-09-10 14:13:38,460:INFO:Creating metrics dataframe
2023-09-10 14:13:38,464:INFO:Uploading results into container
2023-09-10 14:13:38,465:INFO:Uploading model into container now
2023-09-10 14:13:38,466:INFO:_master_model_container: 12
2023-09-10 14:13:38,466:INFO:_display_container: 2
2023-09-10 14:13:38,466:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=6543, verbose=0, warm_start=False)
2023-09-10 14:13:38,466:INFO:create_model() successfully completed......................................
2023-09-10 14:13:38,551:INFO:SubProcess create_model() end ==================================
2023-09-10 14:13:38,552:INFO:Creating metrics dataframe
2023-09-10 14:13:38,563:INFO:Initializing Light Gradient Boosting Machine
2023-09-10 14:13:38,563:INFO:Total runtime is 0.1269485076268514 minutes
2023-09-10 14:13:38,566:INFO:SubProcess create_model() called ==================================
2023-09-10 14:13:38,567:INFO:Initializing create_model()
2023-09-10 14:13:38,567:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f2e40e23a60>, estimator=lightgbm, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f2e40ed2df0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:13:38,567:INFO:Checking exceptions
2023-09-10 14:13:38,567:INFO:Importing libraries
2023-09-10 14:13:38,567:INFO:Copying training dataset
2023-09-10 14:13:38,571:INFO:Defining folds
2023-09-10 14:13:38,571:INFO:Declaring metric variables
2023-09-10 14:13:38,576:INFO:Importing untrained model
2023-09-10 14:13:38,580:INFO:Light Gradient Boosting Machine Imported successfully
2023-09-10 14:13:38,586:INFO:Starting cross validation
2023-09-10 14:13:38,587:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:15:10,800:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:15:10,800:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:15:10,800:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:15:10,800:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:15:11,737:INFO:PyCaret ClassificationExperiment
2023-09-10 14:15:11,737:INFO:Logging name: clf-default-name
2023-09-10 14:15:11,737:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-09-10 14:15:11,737:INFO:version 3.0.4
2023-09-10 14:15:11,737:INFO:Initializing setup()
2023-09-10 14:15:11,737:INFO:self.USI: 3fee
2023-09-10 14:15:11,737:INFO:self._variable_keys: {'log_plots_param', 'idx', 'gpu_param', 'data', 'is_multiclass', 'html_param', 'pipeline', 'USI', 'gpu_n_jobs_param', 'X_test', 'logging_param', 'exp_name_log', '_available_plots', 'fold_shuffle_param', 'fix_imbalance', 'y_train', 'target_param', 'y', 'n_jobs_param', 'seed', 'X_train', 'fold_generator', 'X', 'memory', 'exp_id', '_ml_usecase', 'fold_groups_param', 'y_test'}
2023-09-10 14:15:11,737:INFO:Checking environment
2023-09-10 14:15:11,737:INFO:python_version: 3.8.10
2023-09-10 14:15:11,737:INFO:python_build: ('default', 'May 26 2023 14:05:08')
2023-09-10 14:15:11,737:INFO:machine: x86_64
2023-09-10 14:15:11,737:INFO:platform: Linux-5.15.0-83-generic-x86_64-with-glibc2.29
2023-09-10 14:15:11,737:INFO:Memory: svmem(total=16523304960, available=10478297088, percent=36.6, used=4711952384, free=4433031168, active=2303668224, inactive=7637618688, buffers=538357760, cached=6839963648, shared=982257664, slab=1109045248)
2023-09-10 14:15:11,738:INFO:Physical Core: 4
2023-09-10 14:15:11,738:INFO:Logical Core: 8
2023-09-10 14:15:11,738:INFO:Checking libraries
2023-09-10 14:15:11,738:INFO:System:
2023-09-10 14:15:11,738:INFO:    python: 3.8.10 (default, May 26 2023, 14:05:08)  [GCC 9.4.0]
2023-09-10 14:15:11,738:INFO:executable: /home/sameep/Extra_Projects/DM/venv/bin/python3
2023-09-10 14:15:11,738:INFO:   machine: Linux-5.15.0-83-generic-x86_64-with-glibc2.29
2023-09-10 14:15:11,738:INFO:PyCaret required dependencies:
2023-09-10 14:15:11,759:INFO:                 pip: 23.2.1
2023-09-10 14:15:11,759:INFO:          setuptools: 68.0.0
2023-09-10 14:15:11,759:INFO:             pycaret: 3.0.4
2023-09-10 14:15:11,760:INFO:             IPython: 8.12.2
2023-09-10 14:15:11,760:INFO:          ipywidgets: 8.1.0
2023-09-10 14:15:11,760:INFO:                tqdm: 4.66.1
2023-09-10 14:15:11,760:INFO:               numpy: 1.23.5
2023-09-10 14:15:11,760:INFO:              pandas: 1.5.3
2023-09-10 14:15:11,760:INFO:              jinja2: 3.1.2
2023-09-10 14:15:11,760:INFO:               scipy: 1.10.1
2023-09-10 14:15:11,760:INFO:              joblib: 1.3.2
2023-09-10 14:15:11,760:INFO:             sklearn: 1.2.2
2023-09-10 14:15:11,760:INFO:                pyod: 1.1.0
2023-09-10 14:15:11,760:INFO:            imblearn: 0.11.0
2023-09-10 14:15:11,760:INFO:   category_encoders: 2.6.2
2023-09-10 14:15:11,760:INFO:            lightgbm: 4.0.0
2023-09-10 14:15:11,760:INFO:               numba: 0.57.1
2023-09-10 14:15:11,760:INFO:            requests: 2.31.0
2023-09-10 14:15:11,760:INFO:          matplotlib: 3.7.2
2023-09-10 14:15:11,760:INFO:          scikitplot: 0.3.7
2023-09-10 14:15:11,760:INFO:         yellowbrick: 1.5
2023-09-10 14:15:11,760:INFO:              plotly: 5.16.1
2023-09-10 14:15:11,760:INFO:    plotly-resampler: Not installed
2023-09-10 14:15:11,760:INFO:             kaleido: 0.2.1
2023-09-10 14:15:11,760:INFO:           schemdraw: 0.15
2023-09-10 14:15:11,760:INFO:         statsmodels: 0.14.0
2023-09-10 14:15:11,760:INFO:              sktime: 0.22.0
2023-09-10 14:15:11,760:INFO:               tbats: 1.1.3
2023-09-10 14:15:11,760:INFO:            pmdarima: 2.0.3
2023-09-10 14:15:11,760:INFO:              psutil: 5.9.5
2023-09-10 14:15:11,760:INFO:          markupsafe: 2.1.3
2023-09-10 14:15:11,760:INFO:             pickle5: Not installed
2023-09-10 14:15:11,760:INFO:         cloudpickle: 2.2.1
2023-09-10 14:15:11,760:INFO:         deprecation: 2.1.0
2023-09-10 14:15:11,760:INFO:              xxhash: 3.3.0
2023-09-10 14:15:11,760:INFO:           wurlitzer: 3.0.3
2023-09-10 14:15:11,760:INFO:PyCaret optional dependencies:
2023-09-10 14:15:11,768:INFO:                shap: Not installed
2023-09-10 14:15:11,768:INFO:           interpret: Not installed
2023-09-10 14:15:11,768:INFO:                umap: Not installed
2023-09-10 14:15:11,768:INFO:    pandas_profiling: Not installed
2023-09-10 14:15:11,768:INFO:  explainerdashboard: Not installed
2023-09-10 14:15:11,768:INFO:             autoviz: Not installed
2023-09-10 14:15:11,768:INFO:           fairlearn: Not installed
2023-09-10 14:15:11,768:INFO:          deepchecks: Not installed
2023-09-10 14:15:11,768:INFO:             xgboost: Not installed
2023-09-10 14:15:11,768:INFO:            catboost: Not installed
2023-09-10 14:15:11,768:INFO:              kmodes: Not installed
2023-09-10 14:15:11,768:INFO:             mlxtend: Not installed
2023-09-10 14:15:11,768:INFO:       statsforecast: Not installed
2023-09-10 14:15:11,768:INFO:        tune_sklearn: Not installed
2023-09-10 14:15:11,768:INFO:                 ray: Not installed
2023-09-10 14:15:11,768:INFO:            hyperopt: Not installed
2023-09-10 14:15:11,768:INFO:              optuna: Not installed
2023-09-10 14:15:11,768:INFO:               skopt: Not installed
2023-09-10 14:15:11,768:INFO:              mlflow: Not installed
2023-09-10 14:15:11,768:INFO:              gradio: Not installed
2023-09-10 14:15:11,768:INFO:             fastapi: Not installed
2023-09-10 14:15:11,769:INFO:             uvicorn: Not installed
2023-09-10 14:15:11,769:INFO:              m2cgen: Not installed
2023-09-10 14:15:11,769:INFO:           evidently: Not installed
2023-09-10 14:15:11,769:INFO:               fugue: Not installed
2023-09-10 14:15:11,769:INFO:           streamlit: Not installed
2023-09-10 14:15:11,769:INFO:             prophet: Not installed
2023-09-10 14:15:11,769:INFO:None
2023-09-10 14:15:11,769:INFO:Set up data.
2023-09-10 14:15:11,774:INFO:Set up train/test split.
2023-09-10 14:15:11,778:INFO:Set up index.
2023-09-10 14:15:11,779:INFO:Set up folding strategy.
2023-09-10 14:15:11,779:INFO:Assigning column types.
2023-09-10 14:15:11,782:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-09-10 14:15:11,824:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-09-10 14:15:11,826:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-09-10 14:15:11,850:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:15:11,850:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:15:11,884:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-09-10 14:15:11,884:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-09-10 14:15:11,905:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:15:11,905:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:15:11,906:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-09-10 14:15:11,942:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-09-10 14:15:11,964:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:15:11,964:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:15:12,000:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-09-10 14:15:12,020:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:15:12,020:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:15:12,020:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-09-10 14:15:12,081:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:15:12,082:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:15:12,136:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:15:12,137:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:15:12,138:INFO:Preparing preprocessing pipeline...
2023-09-10 14:15:12,139:INFO:Set up simple imputation.
2023-09-10 14:15:12,154:INFO:Finished creating preprocessing pipeline.
2023-09-10 14:15:12,158:INFO:Pipeline: Pipeline(memory=FastMemory(location=/tmp/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['Pclass', 'Sex', 'Age', 'Fare',
                                             'Embarked', 'Title', 'IsAlone'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose='deprecated'))),
                ('categorical_imputer',
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated')))],
         verbose=False)
2023-09-10 14:15:12,158:INFO:Creating final display dataframe.
2023-09-10 14:15:12,202:INFO:Setup _display_container:                     Description             Value
0                    Session id              6827
1                        Target          Survived
2                   Target type            Binary
3           Original data shape          (891, 8)
4        Transformed data shape          (891, 8)
5   Transformed train set shape          (623, 8)
6    Transformed test set shape          (268, 8)
7              Numeric features                 7
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                10
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              3fee
2023-09-10 14:15:12,287:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:15:12,287:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:15:12,359:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:15:12,360:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:15:12,360:INFO:setup() successfully completed in 0.63s...............
2023-09-10 14:15:12,375:INFO:Initializing compare_models()
2023-09-10 14:15:12,375:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f78416b3a60>, include=None, fold=5, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x7f78416b3a60>, 'include': None, 'exclude': None, 'fold': 5, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-09-10 14:15:12,375:INFO:Checking exceptions
2023-09-10 14:15:12,379:INFO:Preparing display monitor
2023-09-10 14:15:12,404:INFO:Initializing Logistic Regression
2023-09-10 14:15:12,404:INFO:Total runtime is 3.4610430399576825e-06 minutes
2023-09-10 14:15:12,408:INFO:SubProcess create_model() called ==================================
2023-09-10 14:15:12,408:INFO:Initializing create_model()
2023-09-10 14:15:12,408:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f78416b3a60>, estimator=lr, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f78425969a0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:15:12,408:INFO:Checking exceptions
2023-09-10 14:15:12,409:INFO:Importing libraries
2023-09-10 14:15:12,409:INFO:Copying training dataset
2023-09-10 14:15:12,413:INFO:Defining folds
2023-09-10 14:15:12,413:INFO:Declaring metric variables
2023-09-10 14:15:12,416:INFO:Importing untrained model
2023-09-10 14:15:12,419:INFO:Logistic Regression Imported successfully
2023-09-10 14:15:12,427:INFO:Starting cross validation
2023-09-10 14:15:12,428:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:15:14,312:INFO:Calculating mean and std
2023-09-10 14:15:14,315:INFO:Creating metrics dataframe
2023-09-10 14:15:14,326:INFO:Uploading results into container
2023-09-10 14:15:14,328:INFO:Uploading model into container now
2023-09-10 14:15:14,328:INFO:_master_model_container: 1
2023-09-10 14:15:14,328:INFO:_display_container: 2
2023-09-10 14:15:14,329:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=6827, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-09-10 14:15:14,329:INFO:create_model() successfully completed......................................
2023-09-10 14:15:14,402:INFO:SubProcess create_model() end ==================================
2023-09-10 14:15:14,402:INFO:Creating metrics dataframe
2023-09-10 14:15:14,411:INFO:Initializing K Neighbors Classifier
2023-09-10 14:15:14,411:INFO:Total runtime is 0.0334493080774943 minutes
2023-09-10 14:15:14,414:INFO:SubProcess create_model() called ==================================
2023-09-10 14:15:14,414:INFO:Initializing create_model()
2023-09-10 14:15:14,414:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f78416b3a60>, estimator=knn, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f78425969a0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:15:14,414:INFO:Checking exceptions
2023-09-10 14:15:14,414:INFO:Importing libraries
2023-09-10 14:15:14,414:INFO:Copying training dataset
2023-09-10 14:15:14,418:INFO:Defining folds
2023-09-10 14:15:14,418:INFO:Declaring metric variables
2023-09-10 14:15:14,421:INFO:Importing untrained model
2023-09-10 14:15:14,425:INFO:K Neighbors Classifier Imported successfully
2023-09-10 14:15:14,433:INFO:Starting cross validation
2023-09-10 14:15:14,434:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:15:15,543:INFO:Calculating mean and std
2023-09-10 14:15:15,546:INFO:Creating metrics dataframe
2023-09-10 14:15:15,556:INFO:Uploading results into container
2023-09-10 14:15:15,560:INFO:Uploading model into container now
2023-09-10 14:15:15,561:INFO:_master_model_container: 2
2023-09-10 14:15:15,562:INFO:_display_container: 2
2023-09-10 14:15:15,563:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-09-10 14:15:15,563:INFO:create_model() successfully completed......................................
2023-09-10 14:15:15,635:INFO:SubProcess create_model() end ==================================
2023-09-10 14:15:15,635:INFO:Creating metrics dataframe
2023-09-10 14:15:15,645:INFO:Initializing Naive Bayes
2023-09-10 14:15:15,645:INFO:Total runtime is 0.05401975313822428 minutes
2023-09-10 14:15:15,648:INFO:SubProcess create_model() called ==================================
2023-09-10 14:15:15,648:INFO:Initializing create_model()
2023-09-10 14:15:15,648:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f78416b3a60>, estimator=nb, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f78425969a0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:15:15,648:INFO:Checking exceptions
2023-09-10 14:15:15,648:INFO:Importing libraries
2023-09-10 14:15:15,648:INFO:Copying training dataset
2023-09-10 14:15:15,652:INFO:Defining folds
2023-09-10 14:15:15,652:INFO:Declaring metric variables
2023-09-10 14:15:15,654:INFO:Importing untrained model
2023-09-10 14:15:15,661:INFO:Naive Bayes Imported successfully
2023-09-10 14:15:15,683:INFO:Starting cross validation
2023-09-10 14:15:15,684:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:15:15,787:INFO:Calculating mean and std
2023-09-10 14:15:15,788:INFO:Creating metrics dataframe
2023-09-10 14:15:15,793:INFO:Uploading results into container
2023-09-10 14:15:15,794:INFO:Uploading model into container now
2023-09-10 14:15:15,795:INFO:_master_model_container: 3
2023-09-10 14:15:15,795:INFO:_display_container: 2
2023-09-10 14:15:15,795:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-09-10 14:15:15,795:INFO:create_model() successfully completed......................................
2023-09-10 14:15:15,860:INFO:SubProcess create_model() end ==================================
2023-09-10 14:15:15,860:INFO:Creating metrics dataframe
2023-09-10 14:15:15,868:INFO:Initializing Decision Tree Classifier
2023-09-10 14:15:15,868:INFO:Total runtime is 0.057734020551045734 minutes
2023-09-10 14:15:15,871:INFO:SubProcess create_model() called ==================================
2023-09-10 14:15:15,872:INFO:Initializing create_model()
2023-09-10 14:15:15,872:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f78416b3a60>, estimator=dt, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f78425969a0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:15:15,872:INFO:Checking exceptions
2023-09-10 14:15:15,872:INFO:Importing libraries
2023-09-10 14:15:15,872:INFO:Copying training dataset
2023-09-10 14:15:15,876:INFO:Defining folds
2023-09-10 14:15:15,876:INFO:Declaring metric variables
2023-09-10 14:15:15,879:INFO:Importing untrained model
2023-09-10 14:15:15,883:INFO:Decision Tree Classifier Imported successfully
2023-09-10 14:15:15,888:INFO:Starting cross validation
2023-09-10 14:15:15,890:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:15:15,981:INFO:Calculating mean and std
2023-09-10 14:15:15,982:INFO:Creating metrics dataframe
2023-09-10 14:15:15,988:INFO:Uploading results into container
2023-09-10 14:15:15,989:INFO:Uploading model into container now
2023-09-10 14:15:15,990:INFO:_master_model_container: 4
2023-09-10 14:15:15,990:INFO:_display_container: 2
2023-09-10 14:15:15,990:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=6827, splitter='best')
2023-09-10 14:15:15,990:INFO:create_model() successfully completed......................................
2023-09-10 14:15:16,056:INFO:SubProcess create_model() end ==================================
2023-09-10 14:15:16,056:INFO:Creating metrics dataframe
2023-09-10 14:15:16,065:INFO:Initializing SVM - Linear Kernel
2023-09-10 14:15:16,065:INFO:Total runtime is 0.0610276460647583 minutes
2023-09-10 14:15:16,068:INFO:SubProcess create_model() called ==================================
2023-09-10 14:15:16,068:INFO:Initializing create_model()
2023-09-10 14:15:16,068:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f78416b3a60>, estimator=svm, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f78425969a0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:15:16,068:INFO:Checking exceptions
2023-09-10 14:15:16,068:INFO:Importing libraries
2023-09-10 14:15:16,068:INFO:Copying training dataset
2023-09-10 14:15:16,071:INFO:Defining folds
2023-09-10 14:15:16,071:INFO:Declaring metric variables
2023-09-10 14:15:16,075:INFO:Importing untrained model
2023-09-10 14:15:16,079:INFO:SVM - Linear Kernel Imported successfully
2023-09-10 14:15:16,086:INFO:Starting cross validation
2023-09-10 14:15:16,087:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:15:16,135:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 14:15:16,143:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 14:15:16,145:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 14:15:16,149:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 14:15:16,152:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 14:15:16,170:INFO:Calculating mean and std
2023-09-10 14:15:16,171:INFO:Creating metrics dataframe
2023-09-10 14:15:16,176:INFO:Uploading results into container
2023-09-10 14:15:16,177:INFO:Uploading model into container now
2023-09-10 14:15:16,178:INFO:_master_model_container: 5
2023-09-10 14:15:16,178:INFO:_display_container: 2
2023-09-10 14:15:16,178:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=6827, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-09-10 14:15:16,178:INFO:create_model() successfully completed......................................
2023-09-10 14:15:16,244:INFO:SubProcess create_model() end ==================================
2023-09-10 14:15:16,244:INFO:Creating metrics dataframe
2023-09-10 14:15:16,252:INFO:Initializing Ridge Classifier
2023-09-10 14:15:16,252:INFO:Total runtime is 0.06413156588872274 minutes
2023-09-10 14:15:16,254:INFO:SubProcess create_model() called ==================================
2023-09-10 14:15:16,255:INFO:Initializing create_model()
2023-09-10 14:15:16,255:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f78416b3a60>, estimator=ridge, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f78425969a0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:15:16,255:INFO:Checking exceptions
2023-09-10 14:15:16,255:INFO:Importing libraries
2023-09-10 14:15:16,255:INFO:Copying training dataset
2023-09-10 14:15:16,260:INFO:Defining folds
2023-09-10 14:15:16,260:INFO:Declaring metric variables
2023-09-10 14:15:16,263:INFO:Importing untrained model
2023-09-10 14:15:16,266:INFO:Ridge Classifier Imported successfully
2023-09-10 14:15:16,272:INFO:Starting cross validation
2023-09-10 14:15:16,274:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:15:16,326:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 14:15:16,330:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 14:15:16,333:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 14:15:16,333:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 14:15:16,340:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 14:15:16,353:INFO:Calculating mean and std
2023-09-10 14:15:16,354:INFO:Creating metrics dataframe
2023-09-10 14:15:16,360:INFO:Uploading results into container
2023-09-10 14:15:16,361:INFO:Uploading model into container now
2023-09-10 14:15:16,361:INFO:_master_model_container: 6
2023-09-10 14:15:16,361:INFO:_display_container: 2
2023-09-10 14:15:16,361:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=6827, solver='auto',
                tol=0.0001)
2023-09-10 14:15:16,362:INFO:create_model() successfully completed......................................
2023-09-10 14:15:16,426:INFO:SubProcess create_model() end ==================================
2023-09-10 14:15:16,426:INFO:Creating metrics dataframe
2023-09-10 14:15:16,435:INFO:Initializing Random Forest Classifier
2023-09-10 14:15:16,435:INFO:Total runtime is 0.0671836495399475 minutes
2023-09-10 14:15:16,438:INFO:SubProcess create_model() called ==================================
2023-09-10 14:15:16,438:INFO:Initializing create_model()
2023-09-10 14:15:16,438:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f78416b3a60>, estimator=rf, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f78425969a0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:15:16,438:INFO:Checking exceptions
2023-09-10 14:15:16,438:INFO:Importing libraries
2023-09-10 14:15:16,438:INFO:Copying training dataset
2023-09-10 14:15:16,443:INFO:Defining folds
2023-09-10 14:15:16,444:INFO:Declaring metric variables
2023-09-10 14:15:16,446:INFO:Importing untrained model
2023-09-10 14:15:16,449:INFO:Random Forest Classifier Imported successfully
2023-09-10 14:15:16,456:INFO:Starting cross validation
2023-09-10 14:15:16,457:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:15:17,123:INFO:Calculating mean and std
2023-09-10 14:15:17,124:INFO:Creating metrics dataframe
2023-09-10 14:15:17,129:INFO:Uploading results into container
2023-09-10 14:15:17,130:INFO:Uploading model into container now
2023-09-10 14:15:17,131:INFO:_master_model_container: 7
2023-09-10 14:15:17,131:INFO:_display_container: 2
2023-09-10 14:15:17,131:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=6827, verbose=0, warm_start=False)
2023-09-10 14:15:17,131:INFO:create_model() successfully completed......................................
2023-09-10 14:15:17,196:INFO:SubProcess create_model() end ==================================
2023-09-10 14:15:17,196:INFO:Creating metrics dataframe
2023-09-10 14:15:17,205:INFO:Initializing Quadratic Discriminant Analysis
2023-09-10 14:15:17,205:INFO:Total runtime is 0.08002287546793618 minutes
2023-09-10 14:15:17,212:INFO:SubProcess create_model() called ==================================
2023-09-10 14:15:17,212:INFO:Initializing create_model()
2023-09-10 14:15:17,212:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f78416b3a60>, estimator=qda, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f78425969a0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:15:17,212:INFO:Checking exceptions
2023-09-10 14:15:17,214:INFO:Importing libraries
2023-09-10 14:15:17,214:INFO:Copying training dataset
2023-09-10 14:15:17,218:INFO:Defining folds
2023-09-10 14:15:17,218:INFO:Declaring metric variables
2023-09-10 14:15:17,236:INFO:Importing untrained model
2023-09-10 14:15:17,247:INFO:Quadratic Discriminant Analysis Imported successfully
2023-09-10 14:15:17,263:INFO:Starting cross validation
2023-09-10 14:15:17,264:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:15:17,396:INFO:Calculating mean and std
2023-09-10 14:15:17,396:INFO:Creating metrics dataframe
2023-09-10 14:15:17,400:INFO:Uploading results into container
2023-09-10 14:15:17,401:INFO:Uploading model into container now
2023-09-10 14:15:17,401:INFO:_master_model_container: 8
2023-09-10 14:15:17,402:INFO:_display_container: 2
2023-09-10 14:15:17,402:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-09-10 14:15:17,402:INFO:create_model() successfully completed......................................
2023-09-10 14:15:17,469:INFO:SubProcess create_model() end ==================================
2023-09-10 14:15:17,469:INFO:Creating metrics dataframe
2023-09-10 14:15:17,480:INFO:Initializing Ada Boost Classifier
2023-09-10 14:15:17,480:INFO:Total runtime is 0.08459911346435546 minutes
2023-09-10 14:15:17,482:INFO:SubProcess create_model() called ==================================
2023-09-10 14:15:17,483:INFO:Initializing create_model()
2023-09-10 14:15:17,483:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f78416b3a60>, estimator=ada, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f78425969a0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:15:17,483:INFO:Checking exceptions
2023-09-10 14:15:17,483:INFO:Importing libraries
2023-09-10 14:15:17,483:INFO:Copying training dataset
2023-09-10 14:15:17,486:INFO:Defining folds
2023-09-10 14:15:17,486:INFO:Declaring metric variables
2023-09-10 14:15:17,488:INFO:Importing untrained model
2023-09-10 14:15:17,493:INFO:Ada Boost Classifier Imported successfully
2023-09-10 14:15:17,501:INFO:Starting cross validation
2023-09-10 14:15:17,501:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:15:17,862:INFO:Calculating mean and std
2023-09-10 14:15:17,863:INFO:Creating metrics dataframe
2023-09-10 14:15:17,869:INFO:Uploading results into container
2023-09-10 14:15:17,870:INFO:Uploading model into container now
2023-09-10 14:15:17,870:INFO:_master_model_container: 9
2023-09-10 14:15:17,870:INFO:_display_container: 2
2023-09-10 14:15:17,871:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=6827)
2023-09-10 14:15:17,871:INFO:create_model() successfully completed......................................
2023-09-10 14:15:17,950:INFO:SubProcess create_model() end ==================================
2023-09-10 14:15:17,950:INFO:Creating metrics dataframe
2023-09-10 14:15:17,965:INFO:Initializing Gradient Boosting Classifier
2023-09-10 14:15:17,966:INFO:Total runtime is 0.09269686539967854 minutes
2023-09-10 14:15:17,970:INFO:SubProcess create_model() called ==================================
2023-09-10 14:15:17,971:INFO:Initializing create_model()
2023-09-10 14:15:17,971:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f78416b3a60>, estimator=gbc, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f78425969a0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:15:17,971:INFO:Checking exceptions
2023-09-10 14:15:17,971:INFO:Importing libraries
2023-09-10 14:15:17,971:INFO:Copying training dataset
2023-09-10 14:15:17,981:INFO:Defining folds
2023-09-10 14:15:17,982:INFO:Declaring metric variables
2023-09-10 14:15:17,987:INFO:Importing untrained model
2023-09-10 14:15:17,995:INFO:Gradient Boosting Classifier Imported successfully
2023-09-10 14:15:18,007:INFO:Starting cross validation
2023-09-10 14:15:18,009:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:15:18,589:INFO:Calculating mean and std
2023-09-10 14:15:18,590:INFO:Creating metrics dataframe
2023-09-10 14:15:18,599:INFO:Uploading results into container
2023-09-10 14:15:18,599:INFO:Uploading model into container now
2023-09-10 14:15:18,600:INFO:_master_model_container: 10
2023-09-10 14:15:18,600:INFO:_display_container: 2
2023-09-10 14:15:18,600:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=6827, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-09-10 14:15:18,600:INFO:create_model() successfully completed......................................
2023-09-10 14:15:18,680:INFO:SubProcess create_model() end ==================================
2023-09-10 14:15:18,680:INFO:Creating metrics dataframe
2023-09-10 14:15:18,698:INFO:Initializing Linear Discriminant Analysis
2023-09-10 14:15:18,699:INFO:Total runtime is 0.10491357247034708 minutes
2023-09-10 14:15:18,703:INFO:SubProcess create_model() called ==================================
2023-09-10 14:15:18,703:INFO:Initializing create_model()
2023-09-10 14:15:18,703:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f78416b3a60>, estimator=lda, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f78425969a0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:15:18,703:INFO:Checking exceptions
2023-09-10 14:15:18,704:INFO:Importing libraries
2023-09-10 14:15:18,704:INFO:Copying training dataset
2023-09-10 14:15:18,712:INFO:Defining folds
2023-09-10 14:15:18,712:INFO:Declaring metric variables
2023-09-10 14:15:18,717:INFO:Importing untrained model
2023-09-10 14:15:18,722:INFO:Linear Discriminant Analysis Imported successfully
2023-09-10 14:15:18,735:INFO:Starting cross validation
2023-09-10 14:15:18,736:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:15:18,889:INFO:Calculating mean and std
2023-09-10 14:15:18,892:INFO:Creating metrics dataframe
2023-09-10 14:15:18,905:INFO:Uploading results into container
2023-09-10 14:15:18,906:INFO:Uploading model into container now
2023-09-10 14:15:18,907:INFO:_master_model_container: 11
2023-09-10 14:15:18,907:INFO:_display_container: 2
2023-09-10 14:15:18,908:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-09-10 14:15:18,908:INFO:create_model() successfully completed......................................
2023-09-10 14:15:18,985:INFO:SubProcess create_model() end ==================================
2023-09-10 14:15:18,985:INFO:Creating metrics dataframe
2023-09-10 14:15:19,001:INFO:Initializing Extra Trees Classifier
2023-09-10 14:15:19,002:INFO:Total runtime is 0.10996177196502685 minutes
2023-09-10 14:15:19,006:INFO:SubProcess create_model() called ==================================
2023-09-10 14:15:19,007:INFO:Initializing create_model()
2023-09-10 14:15:19,007:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f78416b3a60>, estimator=et, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f78425969a0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:15:19,007:INFO:Checking exceptions
2023-09-10 14:15:19,007:INFO:Importing libraries
2023-09-10 14:15:19,007:INFO:Copying training dataset
2023-09-10 14:15:19,014:INFO:Defining folds
2023-09-10 14:15:19,014:INFO:Declaring metric variables
2023-09-10 14:15:19,019:INFO:Importing untrained model
2023-09-10 14:15:19,026:INFO:Extra Trees Classifier Imported successfully
2023-09-10 14:15:19,035:INFO:Starting cross validation
2023-09-10 14:15:19,036:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:15:19,964:INFO:Calculating mean and std
2023-09-10 14:15:19,965:INFO:Creating metrics dataframe
2023-09-10 14:15:19,979:INFO:Uploading results into container
2023-09-10 14:15:19,980:INFO:Uploading model into container now
2023-09-10 14:15:19,981:INFO:_master_model_container: 12
2023-09-10 14:15:19,981:INFO:_display_container: 2
2023-09-10 14:15:19,982:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=6827, verbose=0, warm_start=False)
2023-09-10 14:15:19,983:INFO:create_model() successfully completed......................................
2023-09-10 14:15:20,052:INFO:SubProcess create_model() end ==================================
2023-09-10 14:15:20,053:INFO:Creating metrics dataframe
2023-09-10 14:15:20,068:INFO:Initializing Light Gradient Boosting Machine
2023-09-10 14:15:20,068:INFO:Total runtime is 0.12773122787475585 minutes
2023-09-10 14:15:20,071:INFO:SubProcess create_model() called ==================================
2023-09-10 14:15:20,072:INFO:Initializing create_model()
2023-09-10 14:15:20,072:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f78416b3a60>, estimator=lightgbm, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f78425969a0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:15:20,072:INFO:Checking exceptions
2023-09-10 14:15:20,073:INFO:Importing libraries
2023-09-10 14:15:20,073:INFO:Copying training dataset
2023-09-10 14:15:20,079:INFO:Defining folds
2023-09-10 14:15:20,079:INFO:Declaring metric variables
2023-09-10 14:15:20,083:INFO:Importing untrained model
2023-09-10 14:15:20,087:INFO:Light Gradient Boosting Machine Imported successfully
2023-09-10 14:15:20,098:INFO:Starting cross validation
2023-09-10 14:15:20,099:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:21:29,772:INFO:Calculating mean and std
2023-09-10 14:21:29,773:INFO:Creating metrics dataframe
2023-09-10 14:21:29,783:INFO:Uploading results into container
2023-09-10 14:21:29,784:INFO:Uploading model into container now
2023-09-10 14:21:29,784:INFO:_master_model_container: 13
2023-09-10 14:21:29,784:INFO:_display_container: 2
2023-09-10 14:21:29,785:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=6827, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2023-09-10 14:21:29,785:INFO:create_model() successfully completed......................................
2023-09-10 14:21:29,844:INFO:SubProcess create_model() end ==================================
2023-09-10 14:21:29,844:INFO:Creating metrics dataframe
2023-09-10 14:21:29,856:INFO:Initializing Dummy Classifier
2023-09-10 14:21:29,856:INFO:Total runtime is 6.290869228045146 minutes
2023-09-10 14:21:29,859:INFO:SubProcess create_model() called ==================================
2023-09-10 14:21:29,859:INFO:Initializing create_model()
2023-09-10 14:21:29,860:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f78416b3a60>, estimator=dummy, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f78425969a0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:21:29,860:INFO:Checking exceptions
2023-09-10 14:21:29,860:INFO:Importing libraries
2023-09-10 14:21:29,860:INFO:Copying training dataset
2023-09-10 14:21:29,863:INFO:Defining folds
2023-09-10 14:21:29,863:INFO:Declaring metric variables
2023-09-10 14:21:29,866:INFO:Importing untrained model
2023-09-10 14:21:29,868:INFO:Dummy Classifier Imported successfully
2023-09-10 14:21:29,876:INFO:Starting cross validation
2023-09-10 14:21:29,877:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:21:29,968:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 14:21:30,015:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 14:21:30,017:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 14:21:30,042:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 14:21:30,043:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 14:21:30,059:INFO:Calculating mean and std
2023-09-10 14:21:30,061:INFO:Creating metrics dataframe
2023-09-10 14:21:30,071:INFO:Uploading results into container
2023-09-10 14:21:30,073:INFO:Uploading model into container now
2023-09-10 14:21:30,074:INFO:_master_model_container: 14
2023-09-10 14:21:30,074:INFO:_display_container: 2
2023-09-10 14:21:30,074:INFO:DummyClassifier(constant=None, random_state=6827, strategy='prior')
2023-09-10 14:21:30,074:INFO:create_model() successfully completed......................................
2023-09-10 14:21:30,156:INFO:SubProcess create_model() end ==================================
2023-09-10 14:21:30,156:INFO:Creating metrics dataframe
2023-09-10 14:21:30,183:INFO:Initializing create_model()
2023-09-10 14:21:30,184:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f78416b3a60>, estimator=GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=6827, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False), fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:21:30,184:INFO:Checking exceptions
2023-09-10 14:21:30,186:INFO:Importing libraries
2023-09-10 14:21:30,186:INFO:Copying training dataset
2023-09-10 14:21:30,192:INFO:Defining folds
2023-09-10 14:21:30,192:INFO:Declaring metric variables
2023-09-10 14:21:30,192:INFO:Importing untrained model
2023-09-10 14:21:30,192:INFO:Declaring custom model
2023-09-10 14:21:30,193:INFO:Gradient Boosting Classifier Imported successfully
2023-09-10 14:21:30,194:INFO:Cross validation set to False
2023-09-10 14:21:30,194:INFO:Fitting Model
2023-09-10 14:21:30,303:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=6827, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-09-10 14:21:30,303:INFO:create_model() successfully completed......................................
2023-09-10 14:21:30,396:INFO:_master_model_container: 14
2023-09-10 14:21:30,397:INFO:_display_container: 2
2023-09-10 14:21:30,397:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=6827, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-09-10 14:21:30,397:INFO:compare_models() successfully completed......................................
2023-09-10 14:26:17,029:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:26:17,029:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:26:17,030:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:26:17,030:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:26:17,904:INFO:PyCaret ClassificationExperiment
2023-09-10 14:26:17,904:INFO:Logging name: clf-default-name
2023-09-10 14:26:17,904:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-09-10 14:26:17,904:INFO:version 3.0.4
2023-09-10 14:26:17,904:INFO:Initializing setup()
2023-09-10 14:26:17,904:INFO:self.USI: fbc0
2023-09-10 14:26:17,904:INFO:self._variable_keys: {'data', 'fold_shuffle_param', 'gpu_param', '_ml_usecase', 'idx', 'pipeline', 'y_test', 'gpu_n_jobs_param', 'target_param', 'seed', 'logging_param', 'X', 'is_multiclass', 'fold_generator', 'fix_imbalance', 'X_test', 'USI', 'y_train', '_available_plots', 'memory', 'n_jobs_param', 'log_plots_param', 'y', 'fold_groups_param', 'X_train', 'exp_name_log', 'exp_id', 'html_param'}
2023-09-10 14:26:17,904:INFO:Checking environment
2023-09-10 14:26:17,904:INFO:python_version: 3.8.10
2023-09-10 14:26:17,904:INFO:python_build: ('default', 'May 26 2023 14:05:08')
2023-09-10 14:26:17,905:INFO:machine: x86_64
2023-09-10 14:26:17,905:INFO:platform: Linux-5.15.0-83-generic-x86_64-with-glibc2.29
2023-09-10 14:26:17,905:INFO:Memory: svmem(total=16523304960, available=10380169216, percent=37.2, used=4822200320, free=4298559488, active=2318991360, inactive=7747579904, buffers=543154176, cached=6859390976, shared=970149888, slab=1112580096)
2023-09-10 14:26:17,905:INFO:Physical Core: 4
2023-09-10 14:26:17,905:INFO:Logical Core: 8
2023-09-10 14:26:17,906:INFO:Checking libraries
2023-09-10 14:26:17,906:INFO:System:
2023-09-10 14:26:17,906:INFO:    python: 3.8.10 (default, May 26 2023, 14:05:08)  [GCC 9.4.0]
2023-09-10 14:26:17,906:INFO:executable: /home/sameep/Extra_Projects/DM/venv/bin/python3
2023-09-10 14:26:17,906:INFO:   machine: Linux-5.15.0-83-generic-x86_64-with-glibc2.29
2023-09-10 14:26:17,906:INFO:PyCaret required dependencies:
2023-09-10 14:26:17,921:INFO:                 pip: 23.2.1
2023-09-10 14:26:17,921:INFO:          setuptools: 68.0.0
2023-09-10 14:26:17,921:INFO:             pycaret: 3.0.4
2023-09-10 14:26:17,921:INFO:             IPython: 8.12.2
2023-09-10 14:26:17,921:INFO:          ipywidgets: 8.1.0
2023-09-10 14:26:17,922:INFO:                tqdm: 4.66.1
2023-09-10 14:26:17,922:INFO:               numpy: 1.23.5
2023-09-10 14:26:17,922:INFO:              pandas: 1.5.3
2023-09-10 14:26:17,922:INFO:              jinja2: 3.1.2
2023-09-10 14:26:17,922:INFO:               scipy: 1.10.1
2023-09-10 14:26:17,922:INFO:              joblib: 1.3.2
2023-09-10 14:26:17,922:INFO:             sklearn: 1.2.2
2023-09-10 14:26:17,922:INFO:                pyod: 1.1.0
2023-09-10 14:26:17,922:INFO:            imblearn: 0.11.0
2023-09-10 14:26:17,922:INFO:   category_encoders: 2.6.2
2023-09-10 14:26:17,922:INFO:            lightgbm: 4.0.0
2023-09-10 14:26:17,922:INFO:               numba: 0.57.1
2023-09-10 14:26:17,922:INFO:            requests: 2.31.0
2023-09-10 14:26:17,922:INFO:          matplotlib: 3.7.2
2023-09-10 14:26:17,922:INFO:          scikitplot: 0.3.7
2023-09-10 14:26:17,922:INFO:         yellowbrick: 1.5
2023-09-10 14:26:17,922:INFO:              plotly: 5.16.1
2023-09-10 14:26:17,922:INFO:    plotly-resampler: Not installed
2023-09-10 14:26:17,922:INFO:             kaleido: 0.2.1
2023-09-10 14:26:17,922:INFO:           schemdraw: 0.15
2023-09-10 14:26:17,922:INFO:         statsmodels: 0.14.0
2023-09-10 14:26:17,922:INFO:              sktime: 0.22.0
2023-09-10 14:26:17,922:INFO:               tbats: 1.1.3
2023-09-10 14:26:17,922:INFO:            pmdarima: 2.0.3
2023-09-10 14:26:17,922:INFO:              psutil: 5.9.5
2023-09-10 14:26:17,922:INFO:          markupsafe: 2.1.3
2023-09-10 14:26:17,922:INFO:             pickle5: Not installed
2023-09-10 14:26:17,922:INFO:         cloudpickle: 2.2.1
2023-09-10 14:26:17,922:INFO:         deprecation: 2.1.0
2023-09-10 14:26:17,922:INFO:              xxhash: 3.3.0
2023-09-10 14:26:17,922:INFO:           wurlitzer: 3.0.3
2023-09-10 14:26:17,922:INFO:PyCaret optional dependencies:
2023-09-10 14:26:17,934:INFO:                shap: Not installed
2023-09-10 14:26:17,935:INFO:           interpret: Not installed
2023-09-10 14:26:17,935:INFO:                umap: Not installed
2023-09-10 14:26:17,935:INFO:    pandas_profiling: Not installed
2023-09-10 14:26:17,935:INFO:  explainerdashboard: Not installed
2023-09-10 14:26:17,935:INFO:             autoviz: Not installed
2023-09-10 14:26:17,935:INFO:           fairlearn: Not installed
2023-09-10 14:26:17,935:INFO:          deepchecks: Not installed
2023-09-10 14:26:17,935:INFO:             xgboost: Not installed
2023-09-10 14:26:17,935:INFO:            catboost: Not installed
2023-09-10 14:26:17,935:INFO:              kmodes: Not installed
2023-09-10 14:26:17,935:INFO:             mlxtend: Not installed
2023-09-10 14:26:17,935:INFO:       statsforecast: Not installed
2023-09-10 14:26:17,935:INFO:        tune_sklearn: Not installed
2023-09-10 14:26:17,935:INFO:                 ray: Not installed
2023-09-10 14:26:17,935:INFO:            hyperopt: Not installed
2023-09-10 14:26:17,935:INFO:              optuna: Not installed
2023-09-10 14:26:17,935:INFO:               skopt: Not installed
2023-09-10 14:26:17,935:INFO:              mlflow: Not installed
2023-09-10 14:26:17,935:INFO:              gradio: Not installed
2023-09-10 14:26:17,935:INFO:             fastapi: Not installed
2023-09-10 14:26:17,935:INFO:             uvicorn: Not installed
2023-09-10 14:26:17,935:INFO:              m2cgen: Not installed
2023-09-10 14:26:17,935:INFO:           evidently: Not installed
2023-09-10 14:26:17,935:INFO:               fugue: Not installed
2023-09-10 14:26:17,935:INFO:           streamlit: Not installed
2023-09-10 14:26:17,935:INFO:             prophet: Not installed
2023-09-10 14:26:17,935:INFO:None
2023-09-10 14:26:17,935:INFO:Set up data.
2023-09-10 14:26:17,945:INFO:Set up train/test split.
2023-09-10 14:26:17,948:INFO:Set up index.
2023-09-10 14:26:17,948:INFO:Set up folding strategy.
2023-09-10 14:26:17,948:INFO:Assigning column types.
2023-09-10 14:26:17,953:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-09-10 14:26:17,989:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-09-10 14:26:17,989:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-09-10 14:26:18,012:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:26:18,013:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:26:18,047:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-09-10 14:26:18,048:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-09-10 14:26:18,070:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:26:18,070:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:26:18,071:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-09-10 14:26:18,105:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-09-10 14:26:18,131:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:26:18,131:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:26:18,167:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-09-10 14:26:18,190:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:26:18,191:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:26:18,191:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-09-10 14:26:18,249:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:26:18,249:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:26:18,308:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:26:18,309:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:26:18,310:INFO:Preparing preprocessing pipeline...
2023-09-10 14:26:18,310:INFO:Set up simple imputation.
2023-09-10 14:26:18,311:INFO:Set up column name cleaning.
2023-09-10 14:26:18,327:INFO:Finished creating preprocessing pipeline.
2023-09-10 14:26:18,331:INFO:Pipeline: Pipeline(memory=FastMemory(location=/tmp/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['Pclass', 'Sex', 'Age', 'Fare',
                                             'Embarked', 'Title', 'IsAlone',
                                             'Age*Class'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose='deprecated'))),
                ('cat...
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+')))],
         verbose=False)
2023-09-10 14:26:18,331:INFO:Creating final display dataframe.
2023-09-10 14:26:18,384:INFO:Setup _display_container:                     Description             Value
0                    Session id              1014
1                        Target          Survived
2                   Target type            Binary
3           Original data shape          (891, 9)
4        Transformed data shape          (891, 9)
5   Transformed train set shape          (623, 9)
6    Transformed test set shape          (268, 9)
7              Numeric features                 8
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                10
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              fbc0
2023-09-10 14:26:18,470:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:26:18,471:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:26:18,528:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:26:18,528:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 14:26:18,528:INFO:setup() successfully completed in 0.63s...............
2023-09-10 14:26:18,547:INFO:Initializing compare_models()
2023-09-10 14:26:18,547:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f6818d187c0>, include=None, fold=5, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x7f6818d187c0>, 'include': None, 'exclude': None, 'fold': 5, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-09-10 14:26:18,547:INFO:Checking exceptions
2023-09-10 14:26:18,551:INFO:Preparing display monitor
2023-09-10 14:26:18,580:INFO:Initializing Logistic Regression
2023-09-10 14:26:18,580:INFO:Total runtime is 2.7934710184733073e-06 minutes
2023-09-10 14:26:18,584:INFO:SubProcess create_model() called ==================================
2023-09-10 14:26:18,584:INFO:Initializing create_model()
2023-09-10 14:26:18,584:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f6818d187c0>, estimator=lr, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f6818d18c70>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:26:18,584:INFO:Checking exceptions
2023-09-10 14:26:18,585:INFO:Importing libraries
2023-09-10 14:26:18,585:INFO:Copying training dataset
2023-09-10 14:26:18,589:INFO:Defining folds
2023-09-10 14:26:18,589:INFO:Declaring metric variables
2023-09-10 14:26:18,592:INFO:Importing untrained model
2023-09-10 14:26:18,595:INFO:Logistic Regression Imported successfully
2023-09-10 14:26:18,607:INFO:Starting cross validation
2023-09-10 14:26:18,608:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:26:20,668:INFO:Calculating mean and std
2023-09-10 14:26:20,672:INFO:Creating metrics dataframe
2023-09-10 14:26:20,683:INFO:Uploading results into container
2023-09-10 14:26:20,686:INFO:Uploading model into container now
2023-09-10 14:26:20,688:INFO:_master_model_container: 1
2023-09-10 14:26:20,688:INFO:_display_container: 2
2023-09-10 14:26:20,689:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=1014, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-09-10 14:26:20,689:INFO:create_model() successfully completed......................................
2023-09-10 14:26:20,777:INFO:SubProcess create_model() end ==================================
2023-09-10 14:26:20,777:INFO:Creating metrics dataframe
2023-09-10 14:26:20,787:INFO:Initializing K Neighbors Classifier
2023-09-10 14:26:20,787:INFO:Total runtime is 0.03678896029790243 minutes
2023-09-10 14:26:20,790:INFO:SubProcess create_model() called ==================================
2023-09-10 14:26:20,791:INFO:Initializing create_model()
2023-09-10 14:26:20,791:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f6818d187c0>, estimator=knn, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f6818d18c70>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:26:20,791:INFO:Checking exceptions
2023-09-10 14:26:20,791:INFO:Importing libraries
2023-09-10 14:26:20,791:INFO:Copying training dataset
2023-09-10 14:26:20,794:INFO:Defining folds
2023-09-10 14:26:20,794:INFO:Declaring metric variables
2023-09-10 14:26:20,798:INFO:Importing untrained model
2023-09-10 14:26:20,804:INFO:K Neighbors Classifier Imported successfully
2023-09-10 14:26:20,812:INFO:Starting cross validation
2023-09-10 14:26:20,813:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:26:22,108:INFO:Calculating mean and std
2023-09-10 14:26:22,110:INFO:Creating metrics dataframe
2023-09-10 14:26:22,121:INFO:Uploading results into container
2023-09-10 14:26:22,122:INFO:Uploading model into container now
2023-09-10 14:26:22,123:INFO:_master_model_container: 2
2023-09-10 14:26:22,123:INFO:_display_container: 2
2023-09-10 14:26:22,124:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-09-10 14:26:22,124:INFO:create_model() successfully completed......................................
2023-09-10 14:26:22,191:INFO:SubProcess create_model() end ==================================
2023-09-10 14:26:22,192:INFO:Creating metrics dataframe
2023-09-10 14:26:22,199:INFO:Initializing Naive Bayes
2023-09-10 14:26:22,200:INFO:Total runtime is 0.060333530108133956 minutes
2023-09-10 14:26:22,204:INFO:SubProcess create_model() called ==================================
2023-09-10 14:26:22,204:INFO:Initializing create_model()
2023-09-10 14:26:22,204:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f6818d187c0>, estimator=nb, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f6818d18c70>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:26:22,204:INFO:Checking exceptions
2023-09-10 14:26:22,204:INFO:Importing libraries
2023-09-10 14:26:22,204:INFO:Copying training dataset
2023-09-10 14:26:22,208:INFO:Defining folds
2023-09-10 14:26:22,208:INFO:Declaring metric variables
2023-09-10 14:26:22,210:INFO:Importing untrained model
2023-09-10 14:26:22,212:INFO:Naive Bayes Imported successfully
2023-09-10 14:26:22,222:INFO:Starting cross validation
2023-09-10 14:26:22,223:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:26:22,382:INFO:Calculating mean and std
2023-09-10 14:26:22,382:INFO:Creating metrics dataframe
2023-09-10 14:26:22,389:INFO:Uploading results into container
2023-09-10 14:26:22,390:INFO:Uploading model into container now
2023-09-10 14:26:22,390:INFO:_master_model_container: 3
2023-09-10 14:26:22,390:INFO:_display_container: 2
2023-09-10 14:26:22,391:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-09-10 14:26:22,391:INFO:create_model() successfully completed......................................
2023-09-10 14:26:22,459:INFO:SubProcess create_model() end ==================================
2023-09-10 14:26:22,459:INFO:Creating metrics dataframe
2023-09-10 14:26:22,467:INFO:Initializing Decision Tree Classifier
2023-09-10 14:26:22,467:INFO:Total runtime is 0.06479494174321493 minutes
2023-09-10 14:26:22,472:INFO:SubProcess create_model() called ==================================
2023-09-10 14:26:22,472:INFO:Initializing create_model()
2023-09-10 14:26:22,472:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f6818d187c0>, estimator=dt, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f6818d18c70>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:26:22,472:INFO:Checking exceptions
2023-09-10 14:26:22,472:INFO:Importing libraries
2023-09-10 14:26:22,472:INFO:Copying training dataset
2023-09-10 14:26:22,476:INFO:Defining folds
2023-09-10 14:26:22,476:INFO:Declaring metric variables
2023-09-10 14:26:22,479:INFO:Importing untrained model
2023-09-10 14:26:22,481:INFO:Decision Tree Classifier Imported successfully
2023-09-10 14:26:22,491:INFO:Starting cross validation
2023-09-10 14:26:22,492:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:26:22,601:INFO:Calculating mean and std
2023-09-10 14:26:22,602:INFO:Creating metrics dataframe
2023-09-10 14:26:22,608:INFO:Uploading results into container
2023-09-10 14:26:22,609:INFO:Uploading model into container now
2023-09-10 14:26:22,609:INFO:_master_model_container: 4
2023-09-10 14:26:22,609:INFO:_display_container: 2
2023-09-10 14:26:22,609:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=1014, splitter='best')
2023-09-10 14:26:22,609:INFO:create_model() successfully completed......................................
2023-09-10 14:26:22,675:INFO:SubProcess create_model() end ==================================
2023-09-10 14:26:22,675:INFO:Creating metrics dataframe
2023-09-10 14:26:22,684:INFO:Initializing SVM - Linear Kernel
2023-09-10 14:26:22,684:INFO:Total runtime is 0.06840672492980958 minutes
2023-09-10 14:26:22,688:INFO:SubProcess create_model() called ==================================
2023-09-10 14:26:22,688:INFO:Initializing create_model()
2023-09-10 14:26:22,689:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f6818d187c0>, estimator=svm, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f6818d18c70>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:26:22,689:INFO:Checking exceptions
2023-09-10 14:26:22,689:INFO:Importing libraries
2023-09-10 14:26:22,689:INFO:Copying training dataset
2023-09-10 14:26:22,692:INFO:Defining folds
2023-09-10 14:26:22,692:INFO:Declaring metric variables
2023-09-10 14:26:22,695:INFO:Importing untrained model
2023-09-10 14:26:22,697:INFO:SVM - Linear Kernel Imported successfully
2023-09-10 14:26:22,706:INFO:Starting cross validation
2023-09-10 14:26:22,707:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:26:22,764:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 14:26:22,768:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 14:26:22,779:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 14:26:22,786:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 14:26:22,793:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 14:26:22,807:INFO:Calculating mean and std
2023-09-10 14:26:22,808:INFO:Creating metrics dataframe
2023-09-10 14:26:22,813:INFO:Uploading results into container
2023-09-10 14:26:22,814:INFO:Uploading model into container now
2023-09-10 14:26:22,814:INFO:_master_model_container: 5
2023-09-10 14:26:22,814:INFO:_display_container: 2
2023-09-10 14:26:22,814:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=1014, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-09-10 14:26:22,814:INFO:create_model() successfully completed......................................
2023-09-10 14:26:22,880:INFO:SubProcess create_model() end ==================================
2023-09-10 14:26:22,881:INFO:Creating metrics dataframe
2023-09-10 14:26:22,891:INFO:Initializing Ridge Classifier
2023-09-10 14:26:22,891:INFO:Total runtime is 0.07185270786285401 minutes
2023-09-10 14:26:22,894:INFO:SubProcess create_model() called ==================================
2023-09-10 14:26:22,894:INFO:Initializing create_model()
2023-09-10 14:26:22,894:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f6818d187c0>, estimator=ridge, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f6818d18c70>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:26:22,894:INFO:Checking exceptions
2023-09-10 14:26:22,894:INFO:Importing libraries
2023-09-10 14:26:22,894:INFO:Copying training dataset
2023-09-10 14:26:22,898:INFO:Defining folds
2023-09-10 14:26:22,898:INFO:Declaring metric variables
2023-09-10 14:26:22,902:INFO:Importing untrained model
2023-09-10 14:26:22,905:INFO:Ridge Classifier Imported successfully
2023-09-10 14:26:22,912:INFO:Starting cross validation
2023-09-10 14:26:22,912:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:26:22,974:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 14:26:22,980:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 14:26:22,988:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 14:26:22,991:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 14:26:23,000:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 14:26:23,018:INFO:Calculating mean and std
2023-09-10 14:26:23,019:INFO:Creating metrics dataframe
2023-09-10 14:26:23,025:INFO:Uploading results into container
2023-09-10 14:26:23,026:INFO:Uploading model into container now
2023-09-10 14:26:23,026:INFO:_master_model_container: 6
2023-09-10 14:26:23,026:INFO:_display_container: 2
2023-09-10 14:26:23,026:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=1014, solver='auto',
                tol=0.0001)
2023-09-10 14:26:23,026:INFO:create_model() successfully completed......................................
2023-09-10 14:26:23,094:INFO:SubProcess create_model() end ==================================
2023-09-10 14:26:23,094:INFO:Creating metrics dataframe
2023-09-10 14:26:23,104:INFO:Initializing Random Forest Classifier
2023-09-10 14:26:23,104:INFO:Total runtime is 0.07540387312571209 minutes
2023-09-10 14:26:23,107:INFO:SubProcess create_model() called ==================================
2023-09-10 14:26:23,107:INFO:Initializing create_model()
2023-09-10 14:26:23,107:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f6818d187c0>, estimator=rf, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f6818d18c70>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:26:23,107:INFO:Checking exceptions
2023-09-10 14:26:23,107:INFO:Importing libraries
2023-09-10 14:26:23,108:INFO:Copying training dataset
2023-09-10 14:26:23,110:INFO:Defining folds
2023-09-10 14:26:23,111:INFO:Declaring metric variables
2023-09-10 14:26:23,113:INFO:Importing untrained model
2023-09-10 14:26:23,117:INFO:Random Forest Classifier Imported successfully
2023-09-10 14:26:23,127:INFO:Starting cross validation
2023-09-10 14:26:23,128:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:26:23,841:INFO:Calculating mean and std
2023-09-10 14:26:23,841:INFO:Creating metrics dataframe
2023-09-10 14:26:23,851:INFO:Uploading results into container
2023-09-10 14:26:23,852:INFO:Uploading model into container now
2023-09-10 14:26:23,853:INFO:_master_model_container: 7
2023-09-10 14:26:23,853:INFO:_display_container: 2
2023-09-10 14:26:23,853:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=1014, verbose=0, warm_start=False)
2023-09-10 14:26:23,853:INFO:create_model() successfully completed......................................
2023-09-10 14:26:23,946:INFO:SubProcess create_model() end ==================================
2023-09-10 14:26:23,946:INFO:Creating metrics dataframe
2023-09-10 14:26:23,957:INFO:Initializing Quadratic Discriminant Analysis
2023-09-10 14:26:23,957:INFO:Total runtime is 0.08961888154347739 minutes
2023-09-10 14:26:23,960:INFO:SubProcess create_model() called ==================================
2023-09-10 14:26:23,960:INFO:Initializing create_model()
2023-09-10 14:26:23,960:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f6818d187c0>, estimator=qda, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f6818d18c70>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:26:23,960:INFO:Checking exceptions
2023-09-10 14:26:23,961:INFO:Importing libraries
2023-09-10 14:26:23,961:INFO:Copying training dataset
2023-09-10 14:26:23,964:INFO:Defining folds
2023-09-10 14:26:23,964:INFO:Declaring metric variables
2023-09-10 14:26:23,969:INFO:Importing untrained model
2023-09-10 14:26:23,974:INFO:Quadratic Discriminant Analysis Imported successfully
2023-09-10 14:26:23,981:INFO:Starting cross validation
2023-09-10 14:26:23,982:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:26:24,103:INFO:Calculating mean and std
2023-09-10 14:26:24,104:INFO:Creating metrics dataframe
2023-09-10 14:26:24,110:INFO:Uploading results into container
2023-09-10 14:26:24,111:INFO:Uploading model into container now
2023-09-10 14:26:24,111:INFO:_master_model_container: 8
2023-09-10 14:26:24,111:INFO:_display_container: 2
2023-09-10 14:26:24,111:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-09-10 14:26:24,111:INFO:create_model() successfully completed......................................
2023-09-10 14:26:24,185:INFO:SubProcess create_model() end ==================================
2023-09-10 14:26:24,185:INFO:Creating metrics dataframe
2023-09-10 14:26:24,196:INFO:Initializing Ada Boost Classifier
2023-09-10 14:26:24,196:INFO:Total runtime is 0.09360318581263226 minutes
2023-09-10 14:26:24,200:INFO:SubProcess create_model() called ==================================
2023-09-10 14:26:24,201:INFO:Initializing create_model()
2023-09-10 14:26:24,201:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f6818d187c0>, estimator=ada, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f6818d18c70>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:26:24,201:INFO:Checking exceptions
2023-09-10 14:26:24,201:INFO:Importing libraries
2023-09-10 14:26:24,201:INFO:Copying training dataset
2023-09-10 14:26:24,206:INFO:Defining folds
2023-09-10 14:26:24,206:INFO:Declaring metric variables
2023-09-10 14:26:24,210:INFO:Importing untrained model
2023-09-10 14:26:24,213:INFO:Ada Boost Classifier Imported successfully
2023-09-10 14:26:24,224:INFO:Starting cross validation
2023-09-10 14:26:24,225:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:26:24,593:INFO:Calculating mean and std
2023-09-10 14:26:24,594:INFO:Creating metrics dataframe
2023-09-10 14:26:24,601:INFO:Uploading results into container
2023-09-10 14:26:24,603:INFO:Uploading model into container now
2023-09-10 14:26:24,603:INFO:_master_model_container: 9
2023-09-10 14:26:24,603:INFO:_display_container: 2
2023-09-10 14:26:24,604:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=1014)
2023-09-10 14:26:24,604:INFO:create_model() successfully completed......................................
2023-09-10 14:26:24,671:INFO:SubProcess create_model() end ==================================
2023-09-10 14:26:24,671:INFO:Creating metrics dataframe
2023-09-10 14:26:24,680:INFO:Initializing Gradient Boosting Classifier
2023-09-10 14:26:24,681:INFO:Total runtime is 0.10168435573577883 minutes
2023-09-10 14:26:24,684:INFO:SubProcess create_model() called ==================================
2023-09-10 14:26:24,685:INFO:Initializing create_model()
2023-09-10 14:26:24,685:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f6818d187c0>, estimator=gbc, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f6818d18c70>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:26:24,686:INFO:Checking exceptions
2023-09-10 14:26:24,686:INFO:Importing libraries
2023-09-10 14:26:24,686:INFO:Copying training dataset
2023-09-10 14:26:24,689:INFO:Defining folds
2023-09-10 14:26:24,690:INFO:Declaring metric variables
2023-09-10 14:26:24,692:INFO:Importing untrained model
2023-09-10 14:26:24,695:INFO:Gradient Boosting Classifier Imported successfully
2023-09-10 14:26:24,704:INFO:Starting cross validation
2023-09-10 14:26:24,705:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:26:25,163:INFO:Calculating mean and std
2023-09-10 14:26:25,163:INFO:Creating metrics dataframe
2023-09-10 14:26:25,174:INFO:Uploading results into container
2023-09-10 14:26:25,175:INFO:Uploading model into container now
2023-09-10 14:26:25,176:INFO:_master_model_container: 10
2023-09-10 14:26:25,176:INFO:_display_container: 2
2023-09-10 14:26:25,176:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=1014, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-09-10 14:26:25,177:INFO:create_model() successfully completed......................................
2023-09-10 14:26:25,272:INFO:SubProcess create_model() end ==================================
2023-09-10 14:26:25,273:INFO:Creating metrics dataframe
2023-09-10 14:26:25,284:INFO:Initializing Linear Discriminant Analysis
2023-09-10 14:26:25,284:INFO:Total runtime is 0.11174221038818362 minutes
2023-09-10 14:26:25,290:INFO:SubProcess create_model() called ==================================
2023-09-10 14:26:25,291:INFO:Initializing create_model()
2023-09-10 14:26:25,291:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f6818d187c0>, estimator=lda, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f6818d18c70>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:26:25,291:INFO:Checking exceptions
2023-09-10 14:26:25,291:INFO:Importing libraries
2023-09-10 14:26:25,291:INFO:Copying training dataset
2023-09-10 14:26:25,295:INFO:Defining folds
2023-09-10 14:26:25,295:INFO:Declaring metric variables
2023-09-10 14:26:25,297:INFO:Importing untrained model
2023-09-10 14:26:25,300:INFO:Linear Discriminant Analysis Imported successfully
2023-09-10 14:26:25,311:INFO:Starting cross validation
2023-09-10 14:26:25,312:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:26:25,470:INFO:Calculating mean and std
2023-09-10 14:26:25,471:INFO:Creating metrics dataframe
2023-09-10 14:26:25,478:INFO:Uploading results into container
2023-09-10 14:26:25,479:INFO:Uploading model into container now
2023-09-10 14:26:25,479:INFO:_master_model_container: 11
2023-09-10 14:26:25,479:INFO:_display_container: 2
2023-09-10 14:26:25,480:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-09-10 14:26:25,480:INFO:create_model() successfully completed......................................
2023-09-10 14:26:25,549:INFO:SubProcess create_model() end ==================================
2023-09-10 14:26:25,550:INFO:Creating metrics dataframe
2023-09-10 14:26:25,561:INFO:Initializing Extra Trees Classifier
2023-09-10 14:26:25,561:INFO:Total runtime is 0.11635168393452965 minutes
2023-09-10 14:26:25,563:INFO:SubProcess create_model() called ==================================
2023-09-10 14:26:25,563:INFO:Initializing create_model()
2023-09-10 14:26:25,563:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f6818d187c0>, estimator=et, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f6818d18c70>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:26:25,564:INFO:Checking exceptions
2023-09-10 14:26:25,564:INFO:Importing libraries
2023-09-10 14:26:25,564:INFO:Copying training dataset
2023-09-10 14:26:25,570:INFO:Defining folds
2023-09-10 14:26:25,570:INFO:Declaring metric variables
2023-09-10 14:26:25,573:INFO:Importing untrained model
2023-09-10 14:26:25,576:INFO:Extra Trees Classifier Imported successfully
2023-09-10 14:26:25,583:INFO:Starting cross validation
2023-09-10 14:26:25,585:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:26:26,244:INFO:Calculating mean and std
2023-09-10 14:26:26,245:INFO:Creating metrics dataframe
2023-09-10 14:26:26,260:INFO:Uploading results into container
2023-09-10 14:26:26,261:INFO:Uploading model into container now
2023-09-10 14:26:26,262:INFO:_master_model_container: 12
2023-09-10 14:26:26,262:INFO:_display_container: 2
2023-09-10 14:26:26,263:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=1014, verbose=0, warm_start=False)
2023-09-10 14:26:26,263:INFO:create_model() successfully completed......................................
2023-09-10 14:26:26,339:INFO:SubProcess create_model() end ==================================
2023-09-10 14:26:26,339:INFO:Creating metrics dataframe
2023-09-10 14:26:26,348:INFO:Initializing Light Gradient Boosting Machine
2023-09-10 14:26:26,348:INFO:Total runtime is 0.12947667439778648 minutes
2023-09-10 14:26:26,352:INFO:SubProcess create_model() called ==================================
2023-09-10 14:26:26,352:INFO:Initializing create_model()
2023-09-10 14:26:26,353:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f6818d187c0>, estimator=lightgbm, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f6818d18c70>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 14:26:26,353:INFO:Checking exceptions
2023-09-10 14:26:26,353:INFO:Importing libraries
2023-09-10 14:26:26,353:INFO:Copying training dataset
2023-09-10 14:26:26,357:INFO:Defining folds
2023-09-10 14:26:26,358:INFO:Declaring metric variables
2023-09-10 14:26:26,360:INFO:Importing untrained model
2023-09-10 14:26:26,365:INFO:Light Gradient Boosting Machine Imported successfully
2023-09-10 14:26:26,375:INFO:Starting cross validation
2023-09-10 14:26:26,376:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 14:31:31,960:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:31:31,960:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:31:31,960:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:31:31,960:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:38:23,390:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

2023-09-10 14:45:34,618:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:45:34,618:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:45:34,618:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:45:34,618:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:45:35,732:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

2023-09-10 14:45:47,870:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:45:47,870:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:45:47,870:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:45:47,870:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:45:48,914:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

2023-09-10 14:46:27,322:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

2023-09-10 14:47:15,920:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:47:15,920:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:47:15,920:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:47:15,920:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 14:47:16,964:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

2023-09-10 14:47:23,286:WARNING:/home/sameep/Extra_Projects/DM/venv/lib/python3.8/site-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

